---
owner: syvtec
repo: guardian
sites:
  - name: Deep Website
    url: https://deepofficegroup.com
  - name: Deep Invoices
    url: https://services.deepofficehub.com
  - name: PrimeCC
    url: https://deepofficehub.com
  - name: Overflow CFM
    url: https://cfm.deepofficehub.com
  - name: Assets Mgt
    url: https://assets.deepofficehub.com
  - name: Velocity
    url: https://velocity.deepofficehub.com
  - name: Inheritance
    url: https://inheritance-intl.com
status-website:
  baseUrl: /guardian
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Guardian
  introTitle: "**Guardian** Syvtec uptime monitor and status page"
  introMessage: This is syvtec status page which uses **real-time** data from
    our [GitHub repository](https://github.com/syvtec/guardian). Powered by Github Pages.
  navbar:
    - title: Status
      href: /guardian
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
